### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by stvogel** [vbhavank/Unstructured-change-detection-using-CNN#1]
Hi Bhavan,

thanks for this great repo. I've seen that your other repositories have a GNU-License-file ... but this has not.
Did you simply forgot a License-file?

Thanks for your help
Stefan

**Comment by vbhavank** [comment]
Hi @stvogel ,

Yes, I did not expect the repo to help so many people when I wrote the code, to be honest. This repo is my implementation of "Mohammed El Amin, Arabi & Liu, Qingjie & Wang, Yunhong. (2016). Convolutional neural network features based change detection in satellite images. 100110W. 10.1117/12.2243798". I will add a license soon.  Thanks! 
Regards
Bhavan

**Comment by stvogel** [comment]
Thank you
