### ISSUE TITLE
Upsampling

### ISSUE THREAD

**Issue by bredebal** [vbhavank/Unstructured-change-detection-using-CNN#2]
Hi,
I manged to run this script with two satellite images but the produced change map has a very low resolution which does not match the original image. What can I do to produce a original resolution change map?

Thanks very much in Advance

Regards, Alex

**Comment by vbhavank** [comment]
Hi Alex(@bredebal ),

Sorry for the late reply. Did you try:
- Pass a larger image in to obtain feature maps with a larger height and width and changing all occurrences to '112x112' to the size of the largest height and width across different stages of the network. Note that the only aspect limiting the use of larger input image size(>224) is resources.

Hope this helps!

**Comment by bredebal** [comment]
Thank you for you're reply. I figured it out already. Thank you again for
you're commit. It was helpful for my university thesis.

Bhavan <notifications@github.com> schrieb am Fr., 28. Feb. 2020, 17:22:

**Comment by vbhavank** [comment]
@bredebal  Great! I am glad you figured it out and this repo helped.  

Cheers! 
Bhavan
